<?php
return[
  '' => 'Seleccione un Municipio',
  'Mazatenango'=>'Mazatenango',
  'Cuyotenango'=>'Cuyotenango',
  'San Francisco Zapotitlán'=>'San Francisco Zapotitlán',
  'San Bernardino'=>'San Bernardino',
  'San José El Idolo'=>'San José El Idolo',
  'Santo Domingo Suchitepequez'=>'Santo Domingo Suchitepequez',
  'San Lorenzo'=>'San Lorenzo',
  'Samayac'=>'Samayac',
  'San Pablo Jocopilas'=>'San Pablo Jocopilas',
  'San Antonio Suchitepequez'=>'San Antonio Suchitepequez',
  'San Miguel Panán'=>'San Miguel Panán',
  'San Gabriel'=>'San Gabriel',
  'Chicacao'=>'Chicacao',
  'Patulul'=>'Patulul',
  'Santa Barbara'=>'Santa Barbara',
  'San Juan Bautista'=>'San Juan Bautista',
  'Santo Tomas La Unión'=>'Santo Tomas La Unión',
  'Zunilito'=>'Zunilito',
  'Pueblo Nuevo'=>'Pueblo Nuevo',
  'Río Bravo'=>'Río Bravo',

];
